# Parameters for compiling

ARDUINO_DIR     = /usr/share/arduino
ARDUINO_VERSION = 10611
ARDMK_DIR       = /usr/share/arduino
ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/avr/cores/arduino
BOARDS_TXT      = /usr/share/arduino/hardware/arduino/avr/boards.txt
ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino/avr/variants
BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino/avr/bootloaders
TARGET          = output
ARDUINO_LIBS    = Adafruit_NeoPixel EEPROM
ARCHITECTURE    = avr


# Avrdude code for programming

BOARD_TAG               = uno
ARDUINO_PORT            = /dev/ttyACM0
AVRDUDE_ARD_PROGRAMMER  = arduino
AVRDUDE_ARD_BAUDRATE    = 115200

# Arduino makefile

include $(ARDUINO_DIR)/Arduino.mk


